title: "Ben George"
description: ""
url: "https://beeegee.github.io"
baseurl: ""

author:
  name: "Ben George"
  github: "beeegee"
  
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: "<!--more-->"

collections:
  notes:
    output: true
    permalink: /notes/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
  - scope:
      path: ""
      type: notes
    values:
      layout: default

giscus:
  repo: "beeegee/beeegee.github.io"
  repo_id: ""
  category: "Announcements"
  category_id: ""

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
